import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import { useEffect } from 'react';
import { useAuthContext } from '../context/AuthContext';


export default function Home() {

  const getCookie = (name) => {
    return document.cookie.split("; ").reduce((r, v) => {
      const parts = v.split("=");
      return parts[0] === name ? decodeURIComponent(parts[1]) : r;
    }, "");
  }
  const { setUser,setToken}= useAuthContext()

  useEffect(()=>{
    let data = getCookie("_site_data");

    if (data !== "") {
      let cookieData = JSON.parse(data);

      // update store
      setToken(cookieData.token.token);
      setUser(
        {
          id: cookieData.user.id,
          first_name: cookieData.user.first_name,
          last_name: cookieData.user.last_name,
          email: cookieData.user.email,
        }
      )
    }
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Book Management System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.LandingPage}>
        <Image
          src='/assets/landing_page.jpeg'
          layout='responsive'
          alt='landing image'
          width={100}
          height={60}
        />


      </div>



    </div>
  )
}
